### ISSUE TITLE
Extract GC from Starlight into separate crate

### ISSUE THREAD

**Issue by playXE** [Starlight-JS/starlight#128]

**Comment by jameslahm** [comment]
I could work on this today ~

**Comment by playXE** [comment]
I'm already working on this: https://github.com/Starlight-JS/starlight-gc

**Comment by jameslahm** [comment]
oh, lol

**Comment by playXE** [comment]
# Update 

Comet is almost complete (https://github.com/Starlight-JS/comet) and I'm slowly starting to integrate it into Starlight. All the work will be in `src/comet.rs` for now. After it is fully integrated into Starlight we will delete `src/gc` and `src/heap` (except snapshot code).

**Comment by playXE** [comment]
Closing this since the new GC works just fine.
