### ISSUE TITLE
Invalid Discord Invitation

### ISSUE THREAD

**Issue by maekawatoshiki** [Starlight-JS/starlight#135]
The invitation link of Discord channel in [README.md](https://github.com/Starlight-JS/starlight/blob/dev/README.md) seems invalid. 
Is it intentional?

**Comment by playXE** [comment]
> Is it intentional?

Hmm, it should be valid. I'll just add link to PLDev discord probably.

**Comment by playXE** [comment]
@maekawatoshiki I updated README.md with https://discord.gg/4Kjt3ZE this link

**Comment by maekawatoshiki** [comment]
It works. Thank you!
