### ISSUE TITLE
Is JsString is_empty correct?

### ISSUE THREAD

**Issue by wezm** [Starlight-JS/Starlight#2]
https://github.com/Starlight-JS/Starlight/blob/19251a26b519d40e7ade00e277a97c1d98dfd6d6/crates/vm/src/runtime/js_string.rs#L19-L21

Seems like it should be `self.len == 0 `?

**Comment by playXE** [comment]
Ah right. I was too asleep when commited this thing. Will fix it soon :) Thanks!

**Comment by playXE** [comment]
Fixed in 3fa11e0310adc5c5073adb9ce937b7c76c8c3203
