### ISSUE TITLE
Any differences with Deno?

### ISSUE THREAD

**Issue by schungx** [Starlight-JS/starlight#23]
As `Deno` is covering TypeScript/ES6 and also written in Rust, is there any major design differences between starlight and Deno?

Any particular design goal that makes this JS engine different?

**Comment by playXE** [comment]
Deno is not an JS engine while Starlight is JS engine. Deno is JS runtime like Node.JS that provides IO/web and other functions to JS, Deno uses V8 engine internally. 

UPD: JS engine is what *executes* JS, JS runtime is what provides additional functionality to what JS engine has

UPD 2: It is correct to compare Starlight to Boa, JavaScriptCore,SpiderMonkey or V8

**Comment by schungx** [comment]
Ah, gotcha.
