### ISSUE TITLE
eval requires return statement

### ISSUE THREAD

**Issue by andrieshiemstra** [Starlight-JS/starlight#29]
Hi, 

I'm building a wrapper for starlight just like my [quickjs](https://github.com/HiRoFa/quickjs_es_runtime) project and i'm bumping into some issues.

When running Runtime.eval() with:
```javascript
(1 + 1)
```
i get a JsValue with type_of() **undefined**.

When i run: 
```javascript
return (1 + 1);
```
i do get a JsValue with type_of(): **number**.

eval should not require a return statement

full example:

```rust
use starlight::vm::{RuntimeParams, GcParams};
use starlight::Platform;

fn main(){
    let options = RuntimeParams::default();
    let gc_params = GcParams::default();
    let mut sl_rt = Platform::new_runtime(options, gc_params, None);
    let script = "(1 + 1);";
    let val = sl_rt.eval(None, true, script, true).ok().expect("script failed");
    println!("typeof = {}", val.type_of());
    // does not work // assert!(val.is_int32());
    let script = "return (1 + 1);";
    let val = sl_rt.eval(None, true, script, true).ok().expect("script failed");
    println!("typeof = {}", val.type_of());
    assert!(val.is_int32());
}
```

**Comment by schungx** [comment]
> eval should not require a return statement

I'm wondering why?  This is JavaScript.

A statement on its own line without an ending semicolon will be added a semicolon.

Without a `return` statement it falls off the end.

Therefore the final value is `undefined`, which is exactly correct.

Are you sure you're not mixing it up with Rust?

**Comment by andrieshiemstra** [comment]
> 
> 
> > eval should not require a return statement
> 
> I'm wondering why? This is JavaScript.
> 
> A statement on its own line without an ending semicolon will be added a semicolon.
> 
> Without a `return` statement it falls off the end.
> 
> Therefore the final value is `undefined`, which is exactly correct.
> 
> Are you sure you're not mixing it up with Rust?

In a function that would be true, and indeed eval is implemented as a function here.

Eval however should not require a return statement (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval)

When using quickjs or spidermonkey it also works like that (without return).

For example see my tests at 
* https://github.com/HiRoFa/spidermonkey_runtime/blob/master/src/esruntime.rs#L324 
* or 
* https://github.com/HiRoFa/quickjs_es_runtime/blob/master/src/quickjscontext.rs#L326

using **return** in eval even results in a _SyntaxError: return not in a function at    at test_eval.es:1_ in quickjs and spidermonkey.

think of eval like loading a file in the browser, you can specify a function but you can't just call return somewhere...

**Comment by schungx** [comment]
> Eval however should not require a return statement

That is the `eval` _function_, which essentially acts as if the script is pasted in the call position as-is.  The return value of the `eval` function is the completion value of the script run, or the last concrete value in the script.

This may be different from `Runtime::eval` which means "evaluate a script", which may not act as though it is JavaScript's `eval` function.  I suppose if the method is renamed `Runtime::run` it may remove the confusion...

**Comment by andrieshiemstra** [comment]
Hmm the probleem is indeed a bit different than i first thought

Eval just compiles the passed script into a function and executes it, therefore you cannot run multiple files, 
e.g. this yields an error _ReferenceError: Property 'a' not found_
```rust
use starlight::vm::{RuntimeParams, GcParams};
use starlight::Platform;
use starlight::prelude::JsValue;

fn main(){
    let options = RuntimeParams::default();
    let gc_params = GcParams::default();
    let mut sl_rt = Platform::new_runtime(options, gc_params, None);
    let script = "let a = 1;";
    let _ = sl_rt.eval(None, true, script, true).ok().expect("script failed");
    let script = "return (a + 1);";
    let val2 = sl_rt.eval(None, true, script, true);
    match val2 {
        Ok(val) => {
            println!("typeof = {}", val.type_of());
            assert!(val.is_int32());
            assert_eq!(val.get_int32(), 2);
        }
        Err(e) => {
            panic!(e.to_string(&mut sl_rt).ok().expect("could not convert"));
        }
    }

}
```

What would be the correct way to load multiple files into starlight?

**Comment by schungx** [comment]
> What would be the correct way to load multiple files into starlight?

Concat the scripts?

You're using a JavaScript engine you know...  not an REPL...

**Comment by andrieshiemstra** [comment]
> 
> 
> > What would be the correct way to load multiple files into starlight?
> 
> Concat the scripts?
> 
> You're using a JavaScript engine you know... not an REPL...

No, that would mess up stacktraces on errors for one, plus every other javascript engine i've ever used supports eval this way.

**Comment by schungx** [comment]
> plus every other javascript engine i've ever used supports eval this way

Those are probably full-blown JavaScript engines that simply defer to the internal `eval` function?

EDIT: To access previous stuff, you need to access the global object (which in a browser is called `window` and on the server is called `global`).  Some engines may encapsulate the engine into the runtime so you can simply keep calling `eval`.

But I don't think starlight is structured like this.

**Comment by andrieshiemstra** [comment]
i guess for file loading it might not be the end of the world (i just need to alter my testcases to use return when evalling if starlight) but for a REPL use case like my commandline client starlight won't work... that's too bad.. i was hoping to add a pure rust engine as an option

**Comment by schungx** [comment]
You may petition the author to add a variation of the `eval` function that takes a global object as input...

**Comment by andrieshiemstra** [comment]
> i guess for file loading it might not be the end of the world.

scratch that, it would mean rewriting stuff like 
```javascript
function a(){
}
```
to
```javascript
global.a = function(){
}
```

And thus the javascript required to run in starlight would never be compatible with javascript used for quickjs or spidermonkey...

**Comment by schungx** [comment]
> And thus the javascript required to run in starlight would never be compatible with javascript used for quickjs or spidermonkey...

That's probably true.  These engines probably encapsulate the global object into the runtime instance.

Sort of like the debug console in a browser...

What you need is an `eval` function that takes a global object as parameter.

**Comment by playXE** [comment]
Hello! Right now `Runtime::eval` does not have ability to return value of last expression or statement in input. What you could do is use `_ = <expr>` which will assign result of `<expr>` to global variable `_` and then get value of that global variable. Also to access global object `globalThis` can be used. Also note that `eval` from ECMAScript standard is not implemented and it will not be implemented any time soon, it requires too much changes on how variables at runtime is handled and how bytecode is emitted. What Starlight has right now is one of the fastest ways to handle variables and implementing eval requires lots of time waste on making variables working fast & correct.

**Comment by andrieshiemstra** [comment]
> 
> 
> Hello! Right now `Runtime::eval` does not have ability to return value of last expression or statement in input. What you could do is use `_ = <expr>` which will assign result of `<expr>` to global variable `_` and then get value of that global variable. Also to access global object `globalThis` can be used. Also note that `eval` from ECMAScript standard is not implemented and it will not be implemented any time soon, it requires too much changes on how variables at runtime is handled and how bytecode is emitted. What Starlight has right now is one of the fastest ways to handle variables and implementing eval requires lots of time waste on making variables working fast & correct.

Thank you for clearing that up!, i was working on a generic way to use different JS engines but i guess i'll just make REPL support optional. I'll look into making the module side of my project work with StarLight.

Currently i'm basing things on quickjs and spidermonkey but would like to have an upgrade path to using a full rust engine in the future so i'm looking at boa and starlight.

Do you have a roadmap or todo-list somewhere with your plans for starlight, e.g. planned support for stuff like classes and async functions? Or would you like me to just open issues for the things that i'm missing?

I think what you've done so far is absolutely awesome by the way! 

Andries

**Comment by playXE** [comment]
> Do you have a roadmap or todo-list somewhere with your plans for starlight, e.g. planned support for stuff like classes and async functions? Or would you like me to just open issues for the things that i'm missing?

You could just open an issue for thing you're missing. :) I do not have roadmap yet. I just implement what is interesting for me. :D

**Comment by andrieshiemstra** [comment]
ok, will do :) i'll close this one and think up some more concerete issues
