### ISSUE TITLE
macOS build segfaults

### ISSUE THREAD

**Issue by playXE** [Starlight-JS/starlight#87]
Something is going wrong on macOS. I do not have macOS machine so I can't debug it

**Comment by jameslahm** [comment]
I'll work on it.

**Comment by playXE** [comment]
@jameslahm looks like 43d3084d8b711b3a637ebad005e207981bbbbb79 solved it but solution is really stupid. approximate_stack_pointer has the same code as I put in collect_internal and I have zero idea why it does work now

**Comment by jameslahm** [comment]
Sorry, I am able to use a macOS machine since tomorrow. I'll try to look into it tomorrow.
