### ISSUE TITLE
Allocate `Realm` on the GC heap and store it in JsGlobal

### ISSUE THREAD

**Issue by playXE** [Starlight-JS/starlight#88]

**Comment by jameslahm** [comment]
I am working on implementing `create intrinsics`. I think `JsGlobal` could be stored in the `realm`. My opinion is that we could store `realm` and `runtime` in a `context`. And each time, `runtime` will first init, creating internal objects. And then `context` be created, storing `runtime` and init `realm`. Last, `context` can `eval` js code. WDYT?

**Comment by playXE** [comment]
We still should have an access to runtime and realm instance from global object. That's what JavaScriptCore has too

**Comment by jameslahm** [comment]
That also makes sense. So we also add `runtimeRef` and `realmRef` in `JsGlobal`? WDYT?

**Comment by playXE** [comment]
> So we also add runtimeRef and realmRef in JsGlobal?

Yep
